import { Patient } from "./types.js";

export const dataPasien: Patient[] = [
    {
      PID: "P001",
      name: "John Doe",
      appointmentTime: "2025-03-21",
      currentMedication: "Sertraline",
      currentDiagnosis: "Major Depressive Disorder",
      riskLevel: "Moderate Risk",
      phone: "+62 81272617398",
      lastVisit: new Date("2025-03-23"),
      NextVisit: new Date("2025-03-24"),
      doctor: "Dr. Aulia Rahman",
      purpose: "Follow-up on medication effectiveness",
      assessment: "Patient shows improvement but still has mild symptoms.",
      status: "Confirmed",
      sessionSummary: "Discussed medication effects and coping strategies."
    },
    {
      PID: "P002",
      name: "Jane Smith",
      appointmentTime: "2025-03-22",
      currentMedication: "Fluoxetine",
      currentDiagnosis: "Generalized Anxiety Disorder",
      riskLevel: "Low Risk",
      phone: "+62 81387263729",
      lastVisit: new Date("2025-03-20"),
      NextVisit: new Date("2025-04-22"),
      doctor: "Dr. Budi Santoso",
      purpose: "Initial consultation",
      assessment: "Patient experiencing moderate anxiety, prescribed therapy.",
      status: "Confirmed",
      sessionSummary: "Introduced cognitive behavioral techniques."
    },
    {
      PID: "P003",
      name: "Michael Johnson",
      appointmentTime: "2025-03-23",
      currentMedication: "Lithium",
      currentDiagnosis: "Bipolar Disorder",
      riskLevel: "High Risk",
      phone: "+62 81283712673",
      lastVisit: new Date("2025-03-15"),
      NextVisit: new Date("2025-03-25"),
      doctor: "Dr. Siti Nurhaliza",
      purpose: "Medication monitoring",
      assessment: "Mood stabilization noted, mild side effects reported.",
      status: "Confirmed",
      sessionSummary: "Adjusted lithium dosage slightly."
    },
    {
      PID: "P004",
      name: "Emily Davis",
      appointmentTime: "2025-03-24",
      currentMedication: "Olanzapine",
      currentDiagnosis: "Schizophrenia",
      riskLevel: "High Risk",
      phone: "+62 81182736281",
      lastVisit: new Date("2025-03-10"),
      NextVisit: new Date("2025-03-28"),
      doctor: "Dr. Hendra Wijaya",
      purpose: "Psychotic episode management",
      assessment: "Symptoms stabilized with current treatment plan.",
      status: "Confirmed",
      sessionSummary: "Encouraged family support involvement."
    },
    {
      PID: "P005",
      name: "Robert Brown",
      appointmentTime: "2025-03-25",
      currentMedication: "Escitalopram",
      currentDiagnosis: "Panic Disorder",
      riskLevel: "Moderate Risk",
      phone: "+62 81237263729",
      lastVisit: new Date("2025-03-18"),
      NextVisit: new Date("2025-04-20"),
      doctor: "Dr. Yasmine Putri",
      purpose: "Progress evaluation",
      assessment: "Panic attacks reduced significantly.",
      status: "Confirmed",
      sessionSummary: "Provided relaxation techniques."
    },
    {
      PID: "P006",
      name: "Sarah Wilson",
      appointmentTime: "2025-03-26",
      currentMedication: "Sertraline",
      currentDiagnosis: "Obsessive-Compulsive Disorder",
      riskLevel: "Low Risk",
      phone: "+62 81372618273",
      lastVisit: new Date("2025-03-12"),
      NextVisit: new Date("2025-04-22"),
      doctor: "Dr. Anwar Prasetyo",
      purpose: "Cognitive therapy session",
      assessment: "Patient learning exposure-response prevention.",
      status: "Confirmed",
      sessionSummary: "Assigned behavioral homework."
    },
    {
      PID: "P007",
      name: "David Martinez",
      appointmentTime: "2025-03-27",
      currentMedication: "Quetiapine",
      currentDiagnosis: "Schizoaffective Disorder",
      riskLevel: "High Risk",
      phone: "+62 81482736281",
      lastVisit: new Date("2025-03-05"),
      NextVisit: new Date("2025-03-30"),
      doctor: "Dr. Fajar Malik",
      purpose: "Medication adherence review",
      assessment: "Patient exhibiting consistent adherence, mild agitation.",
      status: "Confirmed",
      sessionSummary: "Reviewed medication schedule."
    },
    {
      PID: "P008",
      name: "Sophia Taylor",
      appointmentTime: "2025-03-28",
      currentMedication: "Venlafaxine",
      currentDiagnosis: "Post-Traumatic Stress Disorder",
      riskLevel: "Moderate Risk",
      phone: "+62 81582736282",
      lastVisit: new Date("2025-03-14"),
      NextVisit: new Date("2025-04-28"),
      doctor: "Dr. Laksmi Dewi",
      purpose: "Trauma-focused therapy",
      assessment: "Patient engaging well, nightmares still persistent.",
      status: "Confirmed",
      sessionSummary: "Introduced grounding exercises."
    },
    {
      PID: "P009",
      name: "Daniel Anderson",
      appointmentTime: "2025-03-29",
      currentMedication: "Citalopram",
      currentDiagnosis: "Dysthymia",
      riskLevel: "Low Risk",
      phone: "+62 81682736283",
      lastVisit: new Date("2025-03-21"),
      NextVisit: new Date("2025-04-29"),
      doctor: "Dr. Rizky Saputra",
      purpose: "Mood management session",
      assessment: "Mild improvement in mood noted.",
      status: "Uncomfirmed",
      sessionSummary: "Encouraged daily journaling."
    },
    {
      PID: "P010",
      name: "Olivia White",
      appointmentTime: "2025-03-30",
      currentMedication: "Bupropion",
      currentDiagnosis: "Seasonal Affective Disorder",
      riskLevel: "Moderate Risk",
      phone: "+62 81782736284",
      lastVisit: new Date("2025-03-19"),
      NextVisit: new Date("2025-04-30"),
      doctor: "Dr. Nina Kartika",
      purpose: "Light therapy evaluation",
      assessment: "Patient responding well, mood lifting.",
      status: "Confirmed",
      sessionSummary: "Recommended vitamin D supplements."
    }
  ];
  